### ISSUE TITLE
Kubernetes version update/upgrade issue.

### ISSUE THREAD

**Issue by pervrosen** [kairen/kube-ansible#155]
* kube-ansible can be updated without work to kube_version: 1.14.7 in kube-ansible/inventory/group_vars/all.yml

* I cannot upgrade to (latest)stable nor to kube_version: 1.15.X

**Comment by pvr1** [comment]
It seems like we can use version 1.15 up to 1.15.7 since upgrade of roles/k8s-setup/templates/10-kubelet.conf.j2 

THANK YOU! I am very grateful for this as I use this code often to train myself on k8s.

Now, in the same file, —node-labels prevents us (i guess) from upgrading to 1.16. I do not know of the logic to alter node-role.
```
{% if node_role == 'master'  %}
Environment="KUBELET_EXTRA_ARGS=--node-labels=node-role.kubernetes.io/master=''"
{% endif %}
```
From the release doc of 1.16 
kubelet
the --containerized flag was deprecated in 1.14 and has been removed (#80043, @dims)
the beta.kubernetes.io/os and beta.kubernetes.io/arch labels, deprecated since v1.14, are targeted for removal in v1.18.
cAdvisor json endpoints have been deprecated since 1.15. (#78504, @dashpole)
**removed the ability to set kubernetes.io- or k8s.io-prefixed labels via --node-labels, other than the specifically allowed labels/prefixes. (#79305, @paivagustavo)**

**Comment by pervrosen** [comment]
I modified another project for a newer experience. You can find it at 
[https://github.com/pervrosen/kubernetes-cluster](https://github.com/pervrosen/kubernetes-cluster)
Its very basic, but it works now for my intentions. Have fun!
